### ISSUE TITLE
Spline interpolation usage

### ISSUE THREAD

**Issue by jackcarrozzo** [TheRiver/L-MATH#5]
Any chance you could provide an example of using the spline interpolation functionality? I can't figure out the correct manner in which to provide my list of input points.

I have a (nonregularly spaced) list of x,y coords and their values at the given point; is the correct method to make a b-spline instance with the given points as input, then (somehow) evaluate the spline's value at arbitrary x,y points? How are knots related to this?

Thank you!!!

**Comment by TheRiver** [comment]
It's been many years since I've used, yet alone worked on, this library, and I cannot remember entirely the best way to use it, and don't have great examples of using it any more. 

If you have (x,y) coords plus a third value, it sounds like you're working in 3-space. However, I'm not sure that these functions will do what you want. When you evaluate a b-spline (the object returned by the `spline-interpolation` function), you will supply a real valued parameter to evaluate the spline along, rather than an (x, y) pair. If you can make that work for you, I suggest using either the b-spline class, if you want to define the knots yourself, or the spline-interpolation function, if you want to interpolate existing points and have it define the knots for the b-spline itself.

The first argument to the `spline-interpolation` function would be a list of `vector` objects. It's the only required argument. It will return a `b-spline` that you can evaluate using the `evaluate` function. 

Good luck!

**Comment by jackcarrozzo** [comment]
Thanks for the reply! Makes sense.
